export default function ExecutiveDirectorPage() {
  return (
    <>
      <p>Marcello De Feo brings two decades of expertise in application development, web design, and journalism to his role as founder of Bridger Labs. With dual bachelor's degrees in English and Fine Arts, focusing on digital design, and as an MBA candidate at Boston University, he combines creative vision with strategic business acumen. His journey as an award-winning small business owner has provided him with firsthand insights into both the challenges and opportunities that shape entrepreneurial success—experience he now leverages to help other small businesses thrive.</p>
      <p>In his technical career, Marcello has distinguished himself as a full-stack developer, mastering everything from UI/UX design to complex database architecture. His commitment to excellence has earned industry recognition, including a prestigious Webby Awards nomination. Drawing inspiration from both classical and contemporary design principles, he consistently delivers clean, purposeful solutions that drive results.</p>
      <p>Marcello's impact extends beyond technology into meaningful community engagement. His service on the local environmental commission and involvement in main street revitalization initiatives demonstrate his commitment to community development. As the founder of a business collective connecting food and beverage establishments, he facilitated networking opportunities and collaborative events that strengthened the local business ecosystem. His dedication to professional development is evident in his mentorship of junior developers and interns, as well as his leadership of teams up to 30 members. His year of service with AmeriCorps as a technology educator further reflects his commitment to giving back.</p>
      <p>His entrepreneurial portfolio includes founding and successfully exiting a sports media website, later acquired by a radio station and an apparel company. He also established and operated two acclaimed restaurants—an upscale burger establishment and a boutique modern Italian restaurant that became one of the region's most sought-after dining destinations, consistently maintaining near-perfect ratings and a three-month reservation waitlist.</p>
      <p>Throughout his career, Marcello has worked with organizations ranging from small businesses and nonprofits to Fortune 500 companies, including AmerisourceBergen and IKEA. The founding of Bridger Labs represents the culmination of his professional journey, embodying his core values of community building and enabling others' success. A Philadelphia native, he now resides across the bridge with his family, where he continues to foster connections between businesses and their communities.</p>
    </>
  );
}